package com.farhad.example.design_principles02.successive_refinement;

public enum ErrorCode {
	OK, INVALID_ARGUMENT_FORMAT, UNEXPECTED_ARGUMENT, INVALID_ARGUMENT_NAME,
	MISSING_STRING,
	MISSING_INTEGER, INVALID_INTEGER,
	MISSING_DOUBLE, INVALID_DOUBLE
}
